spring:
  session:
    store-type: redis
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 7114

  servlet:
    session:
      cookie:
        name: behtatahvie-panel
    context-path: /

  tomcat:
    max-http-form-post-size: 10MB
api:
  link:

#    behta-server: http://localhost:7411/api
#    behta-thumbnail-url: http://localhost:7411/thumbnail/web/get/

    behta-server: http://localhost:7411/api
    behta-thumbnail-url: http://localhost:7411/thumbnail/web/get/

